apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: myapp
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: mynode
        image: cyberkat7217/calc_web_app:1.1.1
        ports:
        - containerPort: 3040